steps:
  - label: "Local_downlaod"
    commands:
    - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
    - unzip BrowserStackLocal-darwin-x64.zip
  - wait
  - label: "Local_start"
    command: ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon start
  - wait
  - label: "Local_test"
    commands:
      - npm i
      - npx wdio conf/local-test.conf.js
  - label: "Local_stop"
    command: ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon start
