steps:
  - label: "node setup"
    command: "node -v && npm install && npm list && ls"
    key: build

  - label: ":test_tube: Test"
    command: "npm i && npm test"
    key: test
    depends_on: build